### ISSUE TITLE
six for plone.app.ldap

### ISSUE THREAD

**Issue by ermancio** [plone/plone.app.ldap#35]
Hello everybody,
I'm trying to install via buildout (on Windows) plone.app.ldap.
Could you tell what is the exact find-link to use buildout?
Ayway I manually downloaded plone.app.ldap-1.4.3.tar.gz and put in a folder indicated in the buildout.cfg.
Installation requires six...

I'm using Plone 4.2 under WIndows 10.
Any hint?

Luca

**Comment by ermancio** [comment]
This is the message on my prompt

Picked: plone.app.ldap = 1.4.3
Getting required 'zope.schema==4.2.0'
We have the distribution that satisfies 'zope.schema==4.2.0'.
Getting required 'zope.lifecycleevent==3.6.2'
We have the distribution that satisfies 'zope.lifecycleevent==3.6.2'.
Getting required 'zope.interface==3.6.7'
We have the distribution that satisfies 'zope.interface==3.6.7'.
Getting required 'zope.i18nmessageid==3.5.3'
We have the distribution that satisfies 'zope.i18nmessageid==3.5.3'.
Getting required 'zope.component==3.9.5'
We have the distribution that satisfies 'zope.component==3.9.5'.
Getting required 'six'
  required by plone.app.ldap 1.4.3.
We have no distributions for six that satisfies 'six'.
Download error on http://dist.enfoldsystems.com/simple/: timed out -- Some packages may not be found!
Couldn't find index page for 'six' (maybe misspelled?)
Getting distribution for 'six'.
While:
  Installing.
  Getting section zeo.
  Initializing part zeo.
  Getting distribution for 'six'.
Error: Couldn't find a distribution for 'six'.

**Comment by adaugherity** [comment]
Plone 4.2 is ancient; you should really move to at least 4.3.

That aside, six is hosted on the main PyPI site (as is plone.app.ldap), but you probably have an older version of zc.buildout that defaults to using http.  PyPI now requires https (as of October 2017), so you must [configure buildout's index to point to https](https://community.plone.org/t/buildout-not-working-couldnt-find-index-page-for-couldnt-find-a-distribution-disabling-non-https-access-to-apis-on-pypi/5069/13).  Add this to your `[buildout]` section:
```
index = https://pypi.python.org/simple/
```
